### ISSUE TITLE
Uncaught Exception BadMethodCallException: "No session available for this HTTPRequest"

### ISSUE THREAD

**Issue by phptek** [silverstripe/cwp-core#21]
Using `dev-master` (as at `d980d7f049b9b8`) in SilverStripe `test` mode (deployed to SilverStripe Platform UAT) when attempting to login to `/admin` the following exception is thrown:

```
Uncaught Exception BadMethodCallException: "No session available for this HTTPRequest"
at /var/www/mysite/releases/86b5b06b2217d65ec559d90e8e1280e2b2b86039/vendor/silverstripe/framework/src/Control/HTTPRequest.php
line 891
```

This results in an inability to even see the admin login screen, with a 500 error displaying instead.

I traced this back to `Extension/CwpControllerExtension.php` on line 124 where the call to `getSession()` in `$this->owner->getRequest()->getSession()->get('AutoLoginHash')` fails.

To "prove" this is the rogue logic, I removed this `else if` condition, redeployed and I could once again see the admin screen.

The "owner" is the current `Controller` which obviously (should) have a valid `HTTPRequest` object, but I haven't dug any deeper. Over to you @robbieaverill  !?

**Comment by robbieaverill** [comment]
Reproduced, thanks

**Comment by robbieaverill** [comment]
Fix at #22

**Comment by dhensby** [comment]
I believe this will have been fixed by https://github.com/silverstripe/silverstripe-framework/pull/7756

**Comment by robbieaverill** [comment]
Retesting this now

**Comment by robbieaverill** [comment]
Tested on 4.1.x-dev (merged up, contains https://github.com/silverstripe/silverstripe-framework/commit/a8c156a) and it's still a problem

**Comment by tractorcow** [comment]
Right, we have many levels of nested controllers sometimes; Hence the need for the single unified source of truth.

**Comment by Makreig** [comment]
I am still experiencing this on 4.2.1.
I am requesting the session in `onAfterInit` in a Controller extension.

**Comment by robbieaverill** [comment]
@Makreig yeah the second patch for this in core hasn't been released yet: https://github.com/silverstripe/silverstripe-framework/pull/8324
